const products=[
    {
        _id:1,
        name:"Airpods Wireless Bluetooth Headphones",
        image:"/Images/airpod.jpg",
        description:"",
        brand:"Apple",
        category:"Electronics",
        price:"$9.99",
        countInstock:3,
        rating:0,
        numReviews:0,
    },
    {
        _id:2,
        name:"iphone 11 Pro 256GB Memory",
        image:"/Images/iphone.jpg",
        description:"",
        brand:"Apple",
        category:"Electronics",
        price:"$99.99",
        countInstock:10,
        rating:0,
        numReviews:0,
    },
    {
        _id:3,
        name:"Canon EOS 80d DSLR Camera",
        image:"/Images/camera",
        description:"",
        brand:"Canon",
        category:"Electronics",
        price:"$29.99",
        countInstock:0,
        rating:0,
        numReviews:0,
    },
    {
        _id:4,
        name:"Sony Playstation 4 Pro White version",
        image:"/Images/sony",
        description:"",
        brand:"Sony",
        category:"Electronics",
        price:"$99.99",
        countInstock:10,
        rating:0,
        numReviews:0,
    },
    {
        _id:5,
        name:"Logitech G-Series gaming Mouse",
        image:"/Images/mouse",
        description:"",
        brand:"Logitech",
        category:"Electronics",
        price:"$9.99",
        countInstock:7,
        rating:0,
        numReviews:0,
    },
    {
        _id:6,
        name:"Amazon Echo Dot 3rd Generation",
        image:"/Images/amazon",
        description:"",
        brand:"Amazon",
        category:"Electronics",
        price:"$9.99",
        countInstock:0,
        rating:0,
        numReviews:0,
    }
]
export default products;